### ISSUE TITLE
Cannot Build Using Gradle.. Help!

### ISSUE THREAD

**Issue by kathrynchou** [Netflix/ndbench#224]
[kchou@den02tez ndbench]$ gradle --stacktrace | more

FAILURE: Build failed with an exception.

    Where:
    Build file '/scratch/kchou/netflix/real_netflix/ndbench/build.gradle' line: 14

    What went wrong:
    Plugin [id: 'de.undercouch.download', version: '3.4.2'] was not found in any of the following sources:

    Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
    Plugin Repositories (could not resolve plugin artifact 'de.undercouch.download:de.undercouch.download.gradle
    .plugin:3.4.2')
    Searched in the following repositories:
    Gradle Central Plugin Repository

**Comment by kathrynchou** [comment]
home/kchou/netflix/real_netflix/ndbench
[kchou@den02tez ndbench]$ ./gradlew --stacktrace --refresh-dependencies | more
Downloading https://services.gradle.org/distributions/gradle-4.8.1-bin.zip

Exception in thread "main" java.net.ConnectException: Connection timed out (Connection timed out)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:200)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1157)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:66)
        at org.gradle.wrapper.Download.download(Download.java:51)
        at org.gradle.wrapper.Install$1.call(Install.java:62)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

**Comment by vinaykumarchella** [comment]
I am able to clean build and run ndbench without any issues. It must be something related to network settings. Try and see (wget, telnet or curl) if you are able to connect to `https://plugins.gradle.org/m2/de/undercouch/download/` from your terminal.

**Comment by vinaykumarchella** [comment]
Closing this issue as I am assuming it is not an issue anymore
