### ISSUE TITLE
Unable to initialize DynamoDBKeyValue Client because of "Client not found"

### ISSUE THREAD

**Issue by amcp** [Netflix/ndbench#93]
I built the latest commit on the master branch with `./gradlew build` and then started the app with `DISCOVERY_ENV=AWS ./gradlew appRun`.
on GET http://localhost:8080/REST?ndbench/driver/init/DynamoDBKeyValue
I get an error:
{"isSuccess":false,"message":"Client initialization failed!"}

Looking at the tomcat application log, I find the stack trace.
```java
10:11:39,131 ERROR NdBenchResource:208 - Error initializing the client - DynamoDBKeyValue
java.lang.RuntimeException: Client not found: DynamoDBKeyValue
        at com.netflix.ndbench.core.NdBenchClientFactory.getClient(NdBenchClientFactory.java:42)
        at com.netflix.ndbench.core.resources.NdBenchResource.init(NdBenchResource.java:203)
        at java.lang.Thread.run(Thread.java:748)
```

Isn't guice supposed to be doing class path scanning to find all implementations of `NdBenchClient`?

**Comment by vinaykumarchella** [comment]
@ipapapa Can you look into this?

**Comment by ipapapa** [comment]
It seems the DynamoDB plugin does not get loaded
```
11:28:07,747  INFO NdBenchGuiceModule:43 - DISCOVERY_ENV is set to: AWS
11:28:07,954  INFO Reflections:229 - Reflections took 73 ms to scan 11 urls, producing 38 keys and 118 values 
11:28:07,986  INFO NdBenchClientModule:52 - Installing NdBenchClientPlugin: com.netflix.ndbench.plugin.dyno.DynoJedisHashPipeline with Annotation: DynoHashPipeline
11:28:07,987  INFO NdBenchClientModule:52 - Installing NdBenchClientPlugin: com.netflix.ndbench.plugin.es.EsRestPlugin with Annotation: ES_REST
11:28:07,988  INFO NdBenchClientModule:52 - Installing NdBenchClientPlugin: com.netflix.ndbench.plugin.cass.CassAstyanaxPlugin with Annotation: CassAstyanaxPlugin
11:28:07,989  INFO NdBenchClientModule:52 - Installing NdBenchClientPlugin: com.netflix.ndbench.plugin.dyno.DynoJedisGetSetPipeline with Annotation: DynoGetSetPipeline
11:28:07,989  INFO NdBenchClientModule:52 - Installing NdBenchClientPlugin: com.netflix.ndbench.plugin.dyno.DynoJedisExtFunc with Annotation: DynoExtFunc
11:28:07,990  INFO NdBenchClientModule:52 - Installing NdBenchClientPlugin: com.netflix.ndbench.plugin.local.dynomite.proxy.LocalDynomiteProxyPlugin with Annotation: LocalDynomiteProxyPlugin
11:28:07,993  INFO NdBenchClientModule:52 - Installing NdBenchClientPlugin: com.netflix.ndbench.plugins.janusgraph.JanusGraphPluginCQL with Annotation: janusgraph-cql
11:28:08,003  INFO NdBenchClientModule:52 - Installing NdBenchClientPlugin: com.netflix.ndbench.plugin.dyno.DynoJedis with Annotation: DynoJedis
11:28:08,004  INFO NdBenchClientModule:52 - Installing NdBenchClientPlugin: com.netflix.ndbench.plugin.sample.InMemoryTestPlugin with Annotation: InMemoryTest
11:28:08,005  INFO NdBenchClientModule:52 - Installing NdBenchClientPlugin: com.netflix.ndbench.geode.plugin.GeodeCloudPlugin with Annotation: GeodeCloudPlugin
11:28:08,007  INFO NdBenchClientModule:52 - Installing NdBenchClientPlugin: com.netflix.ndbench.plugin.cass.CassJavaDriverGeneric with Annotation: CassJavaDriverGeneric
11:28:08,008  INFO NdBenchClientModule:52 - Installing NdBenchClientPlugin: com.netflix.ndbench.plugin.cass.CassUDTFrozen with Annotation: CassUDTFrozen
11:28:08,009  INFO NdBenchClientModule:52 - Installing NdBenchClientPlugin: com.netflix.ndbench.plugin.cass.CassJavaDriverBatch with Annotation: CassJavaDriverBatch
11:28:08,010  INFO NdBenchClientModule:52 - Installing NdBenchClientPlugin: com.netflix.ndbench.plugin.elassandra.ElassandraCassJavaDriverPlugin with Annotation: ElassandraCassJavaDriverPlugin
11:28:08,051  INFO Reflections:229 - Reflections took 35 ms to scan 11 urls, producing 38 keys and 118 values 
11:28:08,057  INFO NdBenchClientModule:97 - adding ndbench client plugin guice module: com.netflix.ndbench.plugins.janusgraph.NdBenchJanusGraphModule
11:28:08,065  INFO NdBenchClientModule:97 - adding ndbench client plugin guice module: com.netflix.ndbench.plugin.es.NfndbenchEsModule
```
Need to see why it is not getting loaded.

**Comment by ipapapa** [comment]
I am sorry for this issue. We are getting the OSS artifacts and build them internally into a .war that we upload to the EC2 instances. Hence, we do not go through the `appRun` process. We probably need to add that to the Travis test. In any case, the loading of the modules has been fixed in #95.

**Comment by amcp** [comment]
@ipapapa this is why it does not appear in the drop-down list of modules, also. I will verify the fix.

**Comment by amcp** [comment]
@ipapapa make an issue for adding a test of appRun to the travis test?

**Comment by amcp** [comment]
@ipapapa I verified the fix here.

**Comment by ipapapa** [comment]
@amcp Other than adding a test for appRun is there anything else I need to address for this issue?

**Comment by amcp** [comment]
everything is peachy. thanks
